### PR TITLE
Generic SCMA codebooks

### PR DESCRIPTION
**Pull request by klimentyev**
I start work. I moved re_user from Modem_SCMA to Codebook class, because it's a codebook property.
Then I will create the same array for users.

P.S. Now, they are compile time array. Then, I think, we can create dynamic arrays based on codebook file.

### CODE REVIEW

**Comment by klimentyev** [comment]
user_re array was added. I tested based on codebook_basic.cb, so the work needs tests with another codebooks.

**Comment by klimentyev** [comment]
Olivier,
I checked CS1, CS2, CS5. The simulation is correct, but I have one question about BER calculation. For CS5, BER is not equal for users. In our paper from README, we can see, that 2 and 5 users have a worse BER. In our investigations, we average BER. For CS5 at Eb/N0 = 11 dB that BER = 9e-03, but in aff3ct I get BER = 6.5e-4. It's very similar to BER for 1st user. My MATLAB and C code give BER = 6.1e-4 for 1st user and ~1e-3 for 2nd and 5th users.

**Comment by klimentyev** [comment]
It seems that BER is correctly calculated. Perhaps this difference is due to the fact that I use the Log-MPA algorithm in my simulation and AWGN Matlab generator too. Also I used 5 iterations in my simulation, but here at the first time I used 6 iterations MPA. I say about uncoded SCMA.
So, that's correct simulation in aff3ct for all codebooks in AWGN channel :)

**Comment by klimentyev** [comment]
How do you think about friend classes Modem_SCMA and Codebooks? I use getter functions for re_user and user_re from Codebooks in Modem_SCMA. Is friend classes better?

**Comment by OlivierHartmann** [comment]
Hi Vyacheslav,

I am so so sorry! I didn't activated the notifications so I missed you ! So sorry Vyacheslav. I just wanted to ask you where you stand as we just merge our development branch into master branch.

You have worked hard and fast. I check that and I come back to you quickly this time.

**Comment by klimentyev** [comment]
Hi Olivier,

I'm working with documents for my PhD thesis. I hope that I will continue in the middle of November.
Since October, I have not watched the code.

**Comment by OlivierHartmann** [comment]
I have renamed `re_user` to `resource_to_user` and `user_re` to `user_to_resource`. This is much more clear. Was I right ?

Try to use `friend` attributes as little as possible. What you've done with getter methods is perfect.

Could you please send me the command line of what you have tested ? To be sure I reproduce the results with the same parameters.

When I will reproduce your results, I'll try to manage completely dynamic codebook sizes.

Thank you

**Comment by klimentyev** [comment]
> I have renamed `re_user` to `resource_to_user` and `user_re` to `user_to_resource`. This is much more clear. Was I right ?

Yes, you are right.

> 
> Try to use `friend` attributes as little as possible. What you've done with getter methods is perfect.

OK, I understood.

> Could you please send me the command line of what you have tested ? To be sure I reproduce the results with the same parameters.

`./bin/aff3ct --sim-type "BFER" -C "UNCODED" -K "12" -m "13" -M "13" -s "15" --chn-type AWGN --chn-implem FAST --mdm-type "SCMA" --mdm-ite "6" --mnt-max-fe "1000" --src-fra "6" --mdm-codebook ../CS5.cb`

The files with codebooks from here: https://github.com/klimentyev/configuration_files/tree/scma_cb_files/mod/SCMA

For CB1, you can make comparison with the results from here: https://github.com/aff3ct/error_rate_references/tree/master/UNCODED/AWGN/SCMA

> 
> When I will reproduce your results, I'll try to manage completely dynamic codebook sizes.

Thanks!

> 
> Thank you

**Comment by klimentyev** [comment]
Hi Olivier,

I try to run bin from your branch OlivierHartmann:scma_codebook, but after succes build I've errors:

```
# The simulation is running...
(EE) mipp::mul<int32_t> (SSE2) is undefined!
(EE) Backtrace:
(EE) ./bin/aff3ct(+0x95aa2b) [0x558df6f4ea2b]
(EE) ./bin/aff3ct(+0x95f78a) [0x558df6f5378a]
(EE) ./bin/aff3ct(_ZN4mipp3mulIiEEDv4_fS1_S1_+0x4f) [0x558df6f53d7e]
(EE) ./bin/aff3ct(_ZNK4mipp3RegIiE3mulES1_+0x27) [0x558df6f53c73]
(EE) ./bin/aff3ct(_ZNK4mipp3RegIiEmlES1_+0x4e) [0x558df6f53aa8]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools17PRNG_MT19937_simd4seedEN4mipp3RegIiEE+0x12c) [0x558df6f4ef96]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools17PRNG_MT19937_simdC1Ev+0xf2) [0x558df6f4eda0]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools29Gaussian_noise_generator_fastIfEC1Ei+0x53) [0x558df6f26ac3]
(EE) ./bin/aff3ct(_ZNK6aff3ct7factory7Channel10parameters14build_gaussianIfEEPNS_6module7ChannelIT_EEv+0xd9) [0x558df6a874a7]
(EE) ./bin/aff3ct(_ZNK6aff3ct7factory7Channel10parameters5buildIfEEPNS_6module7ChannelIT_EEv+0x30) [0x558df6a86270]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation8BFER_stdIiffE13build_channelEi+0x10c) [0x558df6f17c6e]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation8BFER_stdIiffE27__build_communication_chainEi+0x1b8) [0x558df6f16034]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation4BFERIiffE29start_thread_build_comm_chainEPS2_i+0x4f) [0x558df6ef22d5]
(EE) ./bin/aff3ct(_ZSt13__invoke_implIvPFvPN6aff3ct10simulation4BFERIiffEEiEJS4_iEET_St14__invoke_otherOT0_DpOT1_+0x4c) [0x558df6ef8537]
(EE) ./bin/aff3ct(_ZSt8__invokeIPFvPN6aff3ct10simulation4BFERIiffEEiEJS4_iEENSt15__invoke_resultIT_JDpT0_EE4typeEOS8_DpOS9_+0x66) [0x558df6ef3e2e]
(EE) ./bin/aff3ct(_ZNSt6thread8_InvokerISt5tupleIJPFvPN6aff3ct10simulation4BFERIiffEEiES6_iEEE9_M_invokeIJLm0ELm1ELm2EEEEDTcl8__invokespcl10_S_declvalIXT_EEEEESt12_Index_tupleIJXspT_EEE+0x5f) [0x558df6f037f7]
(EE) ./bin/aff3ct(_ZNSt6thread8_InvokerISt5tupleIJPFvPN6aff3ct10simulation4BFERIiffEEiES6_iEEEclEv+0x2c) [0x558df6f032fc]
(EE) ./bin/aff3ct(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPN6aff3ct10simulation4BFERIiffEEiES7_iEEEEE6_M_runEv+0x1c) [0x558df6f02904]
(EE) /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6(+0xe096e) [0x7fea6ecfa96e]
(EE) /lib64/libpthread.so.0(+0x79aa) [0x7fea6f0239aa]
(EE) /lib64/libc.so.6(clone+0x3f) [0x7fea6e3a18ef]
(EE) mipp::mul<int32_t> (SSE2) is undefined!
(EE) Backtrace:
(EE) ./bin/aff3ct(+0x95aa2b) [0x558df6f4ea2b]
(EE) ./bin/aff3ct(+0x95f78a) [0x558df6f5378a]
(EE) ./bin/aff3ct(_ZN4mipp3mulIiEEDv4_fS1_S1_+0x4f) [0x558df6f53d7e]
(EE) ./bin/aff3ct(_ZNK4mipp3RegIiE3mulES1_+0x27) [0x558df6f53c73]
(EE) ./bin/aff3ct(_ZNK4mipp3RegIiEmlES1_+0x4e) [0x558df6f53aa8]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools17PRNG_MT19937_simd4seedEN4mipp3RegIiEE+0x12c) [0x558df6f4ef96]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools17PRNG_MT19937_simdC1Ev+0xf2) [0x558df6f4eda0]
(EE) ./bin/aff3ct(_ZN6aff3ct5tools29Gaussian_noise_generator_fastIfEC1Ei+0x53) [0x558df6f26ac3]
(EE) ./bin/aff3ct(_ZNK6aff3ct7factory7Channel10parameters14build_gaussianIfEEPNS_6module7ChannelIT_EEv+0xd9) [0x558df6a874a7]
(EE) ./bin/aff3ct(_ZNK6aff3ct7factory7Channel10parameters5buildIfEEPNS_6module7ChannelIT_EEv+0x30) [0x558df6a86270]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation8BFER_stdIiffE13build_channelEi+0x10c) [0x558df6f17c6e]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation8BFER_stdIiffE27__build_communication_chainEi+0x1b8) [0x558df6f16034]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation4BFERIiffE29start_thread_build_comm_chainEPS2_i+0x4f) [0x558df6ef22d5]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation4BFERIiffE26_build_communication_chainEv+0xec) [0x558df6ef16fe]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation10Simulation25build_communication_chainEv+0x32) [0x558df6f22af0]
(EE) ./bin/aff3ct(_ZN6aff3ct10simulation4BFERIiffE6launchEv+0x52) [0x558df6eefae0]
(EE) ./bin/aff3ct(_ZN6aff3ct8launcher8Launcher6launchEv+0x55a) [0x558df6da026a]
(EE) ./bin/aff3ct(main+0x102) [0x558df7006e1e]
(EE) /lib64/libc.so.6(__libc_start_main+0xe7) [0x7fea6e2beb87]
(EE) ./bin/aff3ct(_start+0x2a) [0x558df6a5a27a]
```
I use the next command:
`./bin/aff3ct --sim-type "BFER" -C "UNCODED" -K "12" -m "13" -M "13" -s "15" --chn-type AWGN --chn-implem FAST --mdm-type "SCMA" --mdm-ite "6" --mnt-max-fe "1000" --src-fra "6" --mdm-codebook ../CS5.cb`

What is verison of MIPP correct? I used gcc version 7.3.0 (Gentoo 7.3.0-r3 p1.4).

**Comment by OlivierHartmann** [comment]
Hi,
Use `--chn-implem STD` instead of FAST for quick fix.
Else take a look at the end of [this page](https://github.com/aff3ct/aff3ct/wiki/Specific-compilation-options) and set your architecture flag in your compilation options.

**Comment by klimentyev** [comment]
Thanks!
I used before commands from here: https://github.com/aff3ct/aff3ct#example-of-a-makefile-project-generation-with-the-c-gnu-compiler
with `-DCMAKE_CXX_FLAGS="-funroll-loops -march=native -DMULTI_PREC"`
and `-march=native` was in flags.

**Comment by OlivierHartmann** [comment]
Yes I know sometimes it is wrong. You have to find your architecture and use one of the other flags. What is your CPU?

**Comment by klimentyev** [comment]
Intel Core i7-4790K, it supports all SSE instructions and AVX except AVX-512.
I updated GLIBC from 2.26 to 2.27 at 21.10.2018.
I used `FAST` channel implementation in September. The command line for simulation was copied from my bash history: https://github.com/OlivierHartmann/aff3ct/pull/1#issuecomment-436368113
So I could use the fast channel.

**Comment by OlivierHartmann** [comment]
Try with -mavx512f, else with -mavx2. This is strange that it is trying to use SSE2 instructions.
We're not using GLIBC.

**Comment by OlivierHartmann** [comment]
Sorry, i misread, use -mavx2

**Comment by klimentyev** [comment]
I understood)
I rebuild twice the project without -mavx2. It's works with FAST :)
And I don't understand the phenomenon...
Thx!

**Comment by OlivierHartmann** [comment]
neither do I...

**Comment by klimentyev** [comment]
So I did't change any properties, only several clean/build procedures.

**Pull request merged**
